/** Public processing recipe/artifact contract. Studio managers stay private. */
export {
  PROCESSING_ARTIFACT_VERSION,
  PROCESSING_COMPOSITION_KIND,
  PROCESSING_RECIPE_VERSION,
  canonicalProcessingRecipe,
  fingerprintProcessingRecipe,
  resolvePinnedProcessingChannel,
  validateProcessingArtifactManifest,
  validateProcessingRecipe,
  type ProcessingArtifactManifest,
  type ProcessingChannelDescriptor,
  type ProcessingChannelResolution,
  type ProcessingChannelTiming,
  type ProcessingInput,
  type ProcessingManagerState,
  type ProcessingOperationResult,
  type ProcessingParameters,
  type ProcessingProvenance,
  type ProcessingRecipe,
  type ProcessingScalar,
  type ProcessingStatus,
  type ProcessingWorkspacePort,
  type ProcessingWorkspaceSnapshot,
} from "@framediff/studio-model";
