/** Public processing recipe/artifact contract. Studio managers stay private. */
export {
  PROCESSING_ARTIFACT_VERSION,
  PROCESSING_COMPOSITION_KIND,
  PROCESSING_RECIPE_VERSION,
  RVM_FOREGROUND_CHANNEL,
  RVM_MATTE_CHANNEL,
  RVM_PROCESSOR,
  canonicalProcessingRecipe,
  fingerprintProcessingRecipe,
  resolvePinnedProcessingChannel,
  resolvePinnedProcessingChannelPin,
  validateProcessingArtifactManifest,
  validateProcessingRecipe,
  validateRvmArtifactManifest,
  type ProcessingArtifactManifest,
  type ProcessingChannelPin,
  type ProcessingChannelDescriptor,
  type ProcessingChannelResolution,
  type ProcessingChannelTiming,
  type ProcessingCompositionDocument,
  type ProcessingInput,
  type ProcessingManagerState,
  type ProcessingOperationResult,
  type ProcessingParameters,
  type ProcessingProvenance,
  type ProcessingRecipe,
  type ProcessingScalar,
  type ProcessingStatus,
  type ProcessingWorkspacePort,
  type ProcessingWorkspaceSnapshot,
} from "@framediff/studio-model";
