export { ObservableValue, type Unsubscribe } from "./observable";
export {
  FRAMEDIFF_ASSET_DRAG_MIME,
  parseFramediffAssetDragPayload,
  type FramediffAssetDragPayload,
} from "./assetDrag";
export { StudioSession } from "./StudioSession";
export { StudioApplication } from "./StudioApplication";
export { StudioAgentApi, exposeStudioAgentApi } from "./agent";
export { SourceManager, type SourceState } from "./managers/SourceManager";
export { AssetManager, type AssetState } from "./managers/AssetManager";
export { GitManager, type GitState } from "./managers/GitManager";
export { RenderManager, type RenderExecutor, type RenderState } from "./managers/RenderManager";
export {
  canonicalRenderRequest,
  createRemoteRenderExecutor,
  executeRemoteRender,
  fingerprintRenderRequest,
  RemoteRenderError,
  resumeRemoteRender,
  sanitizeRenderError,
  type RemoteRenderBackend,
  type RemoteRenderPhase,
  type RemoteRenderExecutorOptions,
  type RemoteRenderRequestFactory,
  type RemoteRenderState,
  type RemoteRenderStatus,
  type RemoteRenderSubmission,
  type RenderArtifactMetadata,
  type RenderAssetInput,
  type RenderOutputKind,
  type RenderProgressLike,
  type RenderRational,
  type RenderProvenance,
  type RenderRequest,
  type RenderResultLike,
  type RenderResultMetadata,
  type RenderSettings,
  type RenderSourceRevision,
  type SanitizedRenderError,
  type WaitForRemoteRenderOptions,
} from "./renderContracts";
export {
  PROCESSING_ARTIFACT_VERSION,
  PROCESSING_COMPOSITION_KIND,
  PROCESSING_RECIPE_VERSION,
  ProcessingManager,
  canonicalProcessingRecipe,
  fingerprintProcessingRecipe,
  resolvePinnedProcessingChannel,
  validateProcessingArtifactManifest,
  validateProcessingRecipe,
  type ProcessingArtifactManifest,
  type ProcessingChannelDescriptor,
  type ProcessingChannelResolution,
  type ProcessingChannelTiming,
  type ProcessingInput,
  type ProcessingManagerState,
  type ProcessingOperationResult,
  type ProcessingParameters,
  type ProcessingProvenance,
  type ProcessingRecipe,
  type ProcessingScalar,
  type ProcessingStatus,
  type ProcessingWorkspacePort,
  type ProcessingWorkspaceSnapshot,
} from "./processing";
export { InspectorManager, type InspectorManagerState } from "./managers/InspectorManager";
export { GenerativeManager, type GenerativeManagerState } from "./managers/GenerativeManager";
export { CredentialsManager, type CredentialsManagerState } from "./managers/CredentialsManager";
export { ProjectOperationsManager, type ProjectOperationsState } from "./managers/ProjectOperationsManager";
export { HistoryManager, mergeGroupedReceipts, type HistoryState } from "./managers/HistoryManager";
export { artifactStatusFromInputs, buildTimelineLanes, frontTrimPlacement, packTimelineVisualRows, timelineItemLabel, type FrontTrimResult } from "./timeline";
export { canNestComposition, type NestVerdict } from "./nesting";
export { compositionByReference } from "./compositionRef";
export { renderTargetCompositions, selectedRenderTarget } from "./renderTargets";
export {
  COMPOSITION_KIND_CONTRACTS,
  compositionKindContract,
  compositionKindAuthoringDefaults,
  resolveCompositionAuthoring,
  type CompositionKindContract,
  type CompositionKindAuthoringDefaults,
  type ResolvedCompositionAuthoring,
} from "./authoring";
export {
  fitGesturePath,
  makeArcSegment,
  motionPathToSvg,
  parseMotionPathSvg,
  pointOnCubic,
  sampleGestureByFrame,
  simplifyGesture,
  type CubicMotionSegment,
  type GestureSample,
  type MotionPoint,
} from "./motionPath";
export {
  IDENTITY_AFFINE,
  applyAffine,
  multiplyAffine,
  invertAffine,
  composeAffine,
  previewDeltaToComposition,
  resizeRect,
  type Affine2D,
  type Point2D,
  type Rect2D,
  type ResizeHandle,
} from "./geometry";
export {
  classifyVisualGeometry,
  cropRegionMatchesTargetAspect,
  cropRegionForTargetAspect,
  normalizeCropRegion,
  retargetCropRegion,
  type DimensionRelation,
  type NormalizedCropRegion,
  type VisualAdaptation,
  type VisualFitMode,
  type VisualGeometryClassification,
} from "./generativeGeometry";
export {
  normalizeTweenTrace,
  tweenTracesEqual,
  type CanonicalTweenKind,
  type NormalizedTweenOperation,
  type ParamBinding,
  type ParamKeyframe,
} from "./animation";
export type {
  AnimationClock,
  AgentArtifactSnapshot,
  AgentAssetSnapshot,
  AgentCheckDiagnostic,
  AgentCheckResult,
  AgentCommandEnvelope,
  AgentCommandResult,
  AgentCompositionSnapshot,
  AgentFrameSnapshot,
  AgentProjectSnapshot,
  AgentSemanticCommand,
  AgentSourceRevisionSnapshot,
  AnimationCreateRequest,
  AnimationDiagnosticSnapshot,
  AnimationEditRequest,
  AnimationLiteral,
  AnimationMutation,
  AnimationProbeSnapshot,
  AnimationSnapshot,
  AnimationSourceSpanSnapshot,
  AnimationTimingSnapshot,
  GestureDraftSnapshot,
  AssetDescriptor,
  CacheEntryDescriptor,
  ColorGradeEffectSnapshot,
  CompositionDescriptor,
  CompositionAuthoringDescriptor,
  CompositionKind,
  CompositionOutputKind,
  CompositionTimelineMode,
  CompositionTransportMode,
  ProjectObjectKind,
  ProjectObjectRef,
  PropertyAuthority,
  SourceFileRevisionSnapshot,
  ProjectEditReceipt,
  ProjectEditConflict,
  ProjectEditResult,
  ProjectEditListener,
  CompositionRuntimePort,
  PlacementEditRequest,
  PlacementEditResult,
  PlacementField,
  PlanEditRequest,
  PlanEditIntent,
  ScriptSheetFieldSnapshot,
  ScriptSheetRowSnapshot,
  ScriptSheetSnapshot,
  ScriptSheetSourceSnapshot,
  ScriptSourceEdit,
  TimelineDeleteRequest,
  TimelineShapeCreateRequest,
  MotionPathCreateRequest,
  MotionPathEditRequest,
  MotionPathSnapshot,
  InspectorDetailsSnapshot,
  InspectorControlSnapshot,
  InspectorFieldEditRequest,
  InspectorFieldsEditRequest,
  InspectorFieldSnapshot,
  InspectorOptionSnapshot,
  InspectorSectionSnapshot,
  GenerativeJobSnapshot,
  GenerativeCompositionInputSnapshot,
  GenerativeChoiceSnapshot,
  GenerativeParamSnapshot,
  GenerativeRefSnapshot,
  GenerativeTakeSettingsSnapshot,
  GenerativeTakeSnapshot,
  GenerativeWorkspaceSnapshot,
  NewCompositionKind,
  NewCompositionRequest,
  CompositionBakeInputsSnapshot,
  ProjectOperationResult,
  PreviewHandle,
  PreviewElementEditRequest,
  PreviewElementPatch,
  PreviewElementProperties,
  PreviewNodeSnapshot,
  PreviewOptions,
  ProviderCredentialSnapshot,
  ProviderCredentialsSnapshot,
  ProjectWorkspacePort,
  RenderProgressSnapshot,
  RenderResult,
  StudioRuntimePort,
  StudioGuideDescriptor,
  StudioGuideStep,
  StudioGuideTarget,
  StudioSessionState,
  TimelineContentSnapshot,
  TimelineItemSnapshot,
  TimelineLaneSnapshot,
  UnrollGroupRequest,
  UnrollGroupSnapshot,
} from "./types";
