export { ObservableValue, type Unsubscribe } from "./observable";
export { StudioSession } from "./StudioSession";
export { StudioApplication } from "./StudioApplication";
export { StudioAgentApi, exposeStudioAgentApi } from "./agent";
export { SourceManager, type SourceState } from "./managers/SourceManager";
export { AssetManager, type AssetState } from "./managers/AssetManager";
export { GitManager, type GitState } from "./managers/GitManager";
export { RenderManager, type RenderState } from "./managers/RenderManager";
export { InspectorManager, type InspectorManagerState } from "./managers/InspectorManager";
export { GenerativeManager, type GenerativeManagerState } from "./managers/GenerativeManager";
export { ProjectOperationsManager, type ProjectOperationsState } from "./managers/ProjectOperationsManager";
export { HistoryManager, mergeGroupedReceipts, type HistoryState } from "./managers/HistoryManager";
export { artifactStatusFromInputs, buildTimelineLanes, frontTrimPlacement, timelineItemLabel, type FrontTrimResult } from "./timeline";
export { canNestComposition, type NestVerdict } from "./nesting";
export {
  fitGesturePath,
  makeArcSegment,
  motionPathToSvg,
  parseMotionPathSvg,
  pointOnCubic,
  sampleGestureByFrame,
  simplifyGesture,
  type CubicMotionSegment,
  type GestureSample,
  type MotionPoint,
} from "./motionPath";
export {
  IDENTITY_AFFINE,
  applyAffine,
  multiplyAffine,
  invertAffine,
  composeAffine,
  previewDeltaToComposition,
  resizeRect,
  type Affine2D,
  type Point2D,
  type Rect2D,
  type ResizeHandle,
} from "./geometry";
export {
  normalizeTweenTrace,
  tweenTracesEqual,
  type CanonicalTweenKind,
  type NormalizedTweenOperation,
  type ParamBinding,
  type ParamKeyframe,
} from "./animation";
export type {
  AnimationClock,
  AgentArtifactSnapshot,
  AgentAssetSnapshot,
  AgentCheckDiagnostic,
  AgentCheckResult,
  AgentCommandEnvelope,
  AgentCommandResult,
  AgentCompositionSnapshot,
  AgentFrameSnapshot,
  AgentProjectSnapshot,
  AgentSemanticCommand,
  AgentSourceRevisionSnapshot,
  AnimationCreateRequest,
  AnimationDiagnosticSnapshot,
  AnimationEditRequest,
  AnimationLiteral,
  AnimationMutation,
  AnimationProbeSnapshot,
  AnimationSnapshot,
  AnimationSourceSpanSnapshot,
  AnimationTimingSnapshot,
  GestureDraftSnapshot,
  AssetDescriptor,
  CacheEntryDescriptor,
  ColorGradeEffectSnapshot,
  CompositionDescriptor,
  CompositionKind,
  CompositionOutputKind,
  ProjectObjectKind,
  ProjectObjectRef,
  PropertyAuthority,
  SourceFileRevisionSnapshot,
  ProjectEditReceipt,
  ProjectEditConflict,
  ProjectEditResult,
  ProjectEditListener,
  CompositionRuntimePort,
  PlacementEditRequest,
  PlacementEditResult,
  PlacementField,
  MotionPathCreateRequest,
  MotionPathEditRequest,
  MotionPathSnapshot,
  InspectorDetailsSnapshot,
  InspectorControlSnapshot,
  InspectorFieldEditRequest,
  InspectorFieldsEditRequest,
  InspectorFieldSnapshot,
  InspectorOptionSnapshot,
  InspectorSectionSnapshot,
  GenerativeJobSnapshot,
  GenerativeCompositionInputSnapshot,
  GenerativeParamSnapshot,
  GenerativeRefSnapshot,
  GenerativeTakeSettingsSnapshot,
  GenerativeTakeSnapshot,
  GenerativeWorkspaceSnapshot,
  NewCompositionKind,
  NewCompositionRequest,
  ProjectOperationResult,
  PreviewHandle,
  PreviewElementEditRequest,
  PreviewElementPatch,
  PreviewElementProperties,
  PreviewNodeSnapshot,
  PreviewOptions,
  ProjectWorkspacePort,
  RenderProgressSnapshot,
  RenderResult,
  StudioRuntimePort,
  StudioGuideDescriptor,
  StudioGuideStep,
  StudioGuideTarget,
  StudioSessionState,
  TimelineContentSnapshot,
  TimelineItemSnapshot,
  TimelineLaneSnapshot,
  UnrollGroupRequest,
  UnrollGroupSnapshot,
} from "./types";
